param (
    [string]$RepoOwner = "DeCEll-1",
    [string]$RepoName  = "CustomizablePhaseGlow"
)

$Token = $env:GITHUB_TOKEN
$Headers = @{
    "Accept"        = "application/vnd.github+json"
    "Authorization" = "Bearer $Token"
}

# 1. Fetch current live snapshot data from the API
$Uri = "https://api.github.com/repos/$RepoOwner/$RepoName/releases"
try {
    $Releases = Invoke-RestMethod -Uri $Uri -Method Get -Headers $Headers -ErrorAction Stop
} catch {
    Write-Error "Failed to fetch releases from GitHub API: $_"
    exit 1
}

# Capture current normalized timestamp for this data logging event
$SnapshotDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# 2. Extract current total download metrics
$CurrentMetrics = foreach ($Release in $Releases) {
    $TotalDownloads = ($Release.assets | Measure-Object -Property download_count -Sum).Sum
    if ($null -eq $TotalDownloads) { $TotalDownloads = 0 }

    [PSCustomObject]@{
        SnapshotDate   = $SnapshotDate
        ReleaseTag     = $Release.tag_name
        PublishedAt    = $Release.published_at
        TotalDownloads = [int]$TotalDownloads
    }
}

# 3. Setup output file paths
$OutputPath = "./AutoGenerated/download_data.json"
$TargetDir  = Split-Path $OutputPath -Parent
if (-not (Test-Path $TargetDir)) {
    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
}

# 4. Handle Historical Merging
$HistoricalData = @()

if (Test-Path $OutputPath) {
    try {
        # Read the existing file content
        $RawJson = Get-Content -Raw -Path $OutputPath -ErrorAction Stop
        if (-not [string]::IsNullOrWhiteSpace($RawJson)) {
            # Convert JSON array back to PowerShell arrays/objects
            $HistoricalData = ConvertFrom-Json $RawJson
        }
    } catch {
        Write-Warning "Existing JSON file was corrupt or unreadable. Starting fresh history tracking. Error: $_"
    }
}

# Combine the old array data with the new array metrics
$CombinedData = @($HistoricalData) + @($CurrentMetrics)

# 5. Output the complete historical list back to disk
$CombinedData | ConvertTo-Json -Depth 5 | Out-File -FilePath $OutputPath -Encoding utf8

Write-Host "Successfully updated historical telemetry log at $OutputPath!"