param (
    [string]$RepoOwner = "DeCEll-1",
    [string]$RepoName  = "CustomizablePhaseGlow"
)

$Token = $env:GITHUB_TOKEN
$Headers = @{
    "Accept"        = "application/vnd.github+json"
    "Authorization" = "Bearer $Token"
}

# 1. Fetch current live snapshot data from the API
$Uri = "https://api.github.com/repos/$RepoOwner/$RepoName/releases"
try {
    $Releases = Invoke-RestMethod -Uri $Uri -Method Get -Headers $Headers -ErrorAction Stop
} catch {
    Write-Error "Failed to fetch releases from GitHub API: $_"
    exit 1
}

# Capture current normalized timestamp for this data logging event
$SnapshotDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# 2. Extract total download metrics combined, labeled with the latest release tag
$LatestReleaseTag = $Releases[0].tag_name
$LatestPublishedAt = $Releases[0].published_at

# Loop through all releases to sum up every custom asset's download count
$TotalRepoDownloads = 0
foreach ($Release in $Releases) {
    $ReleaseSum = ($Release.assets | Measure-Object -Property download_count -Sum).Sum
    if ($null -ne $ReleaseSum) {
        $TotalRepoDownloads += $ReleaseSum
    }
}

# Create one clean, combined snapshot object
$CurrentMetrics = [PSCustomObject]@{
    SnapshotDate   = $SnapshotDate
    ReleaseTag     = $LatestReleaseTag
    PublishedAt    = $LatestPublishedAt
    TotalDownloads = [int]$TotalRepoDownloads
}

# 3. Setup output file paths
$OutputPath = "./AutoGenerated/download_data.json"
$TargetDir  = Split-Path $OutputPath -Parent
if (-not (Test-Path $TargetDir)) {
    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
}

# 4. Handle Historical Merging
$HistoricalData = @()

if (Test-Path $OutputPath) {
    try {
        # Read the existing file content
        $RawJson = Get-Content -Raw -Path $OutputPath -ErrorAction Stop
        if (-not [string]::IsNullOrWhiteSpace($RawJson)) {
            # Convert JSON array back to PowerShell arrays/objects
            $HistoricalData = ConvertFrom-Json $RawJson
        }
    } catch {
        Write-Warning "Existing JSON file was corrupt or unreadable. Starting fresh history tracking. Error: $_"
    }
}

# Combine the old array data with the new array metrics
$CombinedData = @($HistoricalData) + @($CurrentMetrics)

# 5. Output the complete historical list back to disk
$CombinedData | ConvertTo-Json -Depth 5 | Out-File -FilePath $OutputPath -Encoding utf8

Write-Host "Successfully updated historical telemetry log at $OutputPath!"